-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Apr 28, 2023 at 04:40 AM
-- Server version: 8.0.31
-- PHP Version: 8.0.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `uecs2094_website`
--

-- --------------------------------------------------------

--
-- Table structure for table `cart`
--

DROP TABLE IF EXISTS `cart`;
CREATE TABLE IF NOT EXISTS `cart` (
  `cartID` int NOT NULL AUTO_INCREMENT,
  `itemID` int NOT NULL,
  `userID` int NOT NULL,
  PRIMARY KEY (`cartID`),
  KEY `userID` (`userID`),
  KEY `itemID` (`itemID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `contact`
--

DROP TABLE IF EXISTS `contact`;
CREATE TABLE IF NOT EXISTS `contact` (
  `contactID` int NOT NULL AUTO_INCREMENT,
  `userID` int NOT NULL,
  `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `gender` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `message` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `posted` datetime DEFAULT NULL,
  PRIMARY KEY (`contactID`),
  KEY `userID` (`userID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

DROP TABLE IF EXISTS `products`;
CREATE TABLE IF NOT EXISTS `products` (
  `product_id` int NOT NULL AUTO_INCREMENT,
  `product_name` varchar(50) NOT NULL,
  `product_price` decimal(10,2) NOT NULL,
  `product_gender` varchar(255) NOT NULL,
  `product_description` longtext NOT NULL,
  `product_image` varchar(100) NOT NULL,
  PRIMARY KEY (`product_id`)
) ENGINE=MyISAM AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb3;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_gender`, `product_description`, `product_image`) VALUES
(1, 'Plain Blue Shirt', '75.00', 'Male', 'This comfortable and classic blue t-shirt is a must-have addition to any wardrobe. The shirt is made of soft and breathable cotton material, which feels great against the skin. The plain design is simple and versatile, making it easy to pair with a variety of different outfits. The color is a cool shade of blue that\'s perfect for any season and occasion. The shirt has a relaxed fit and short sleeves, making it comfortable to wear all day long. This t-shirt is a timeless staple that every guy should have in his collection.', 'product_images/Male/MaleShirt1.jpeg'),
(2, 'Classic Black Plain T', '70.00', 'Male', 'This classic black t-shirt is a versatile and stylish choice for any occasion. Made from high-quality cotton material, this shirt is soft and breathable, making it comfortable to wear all day long. The plain design gives it a timeless look that pairs well with any outfit. The sleek black color is perfect for dressing up or down, and the short sleeves make it great for layering or wearing on its own. The shirt has a relaxed fit that provides a comfortable and flattering silhouette. Whether you\'re running errands or heading out for a night on the town, this black t-shirt is a must-have item for any man\'s wardrobe.', 'product_images/Male/MaleShirt2.jpeg'),
(3, 'White Long loose', '90.00', 'Male', ' Upgrade your wardrobe with these stylish and comfortable white long pants for men. Made from high-quality cotton material, these pants are soft, breathable, and perfect for all-day wear. The pants feature a classic and versatile design that can be dressed up or down depending on the occasion. The white color provides a clean and sophisticated look that pairs well with any shirt or jacket. The pants have a relaxed fit and a straight leg cut that provides a comfortable and flattering silhouette. They also feature front and back pockets, making them practical and convenient. Whether you\'re headed to the office or going out for a night on the town, these white long pants are the perfect choice. They\'re versatile, comfortable, and stylish, making them a must-have item for any man\'s wardrobe.', 'product_images/Male/MalePants1.jpg'),
(4, 'Short Style', '80.00', 'Male', 'Get ready for warm weather with these stylish and comfortable chocolate brown shorts for men. Made from high-quality cotton material, these shorts are soft, breathable, and perfect for all-day wear. The chocolate brown color provides a rich and versatile look that pairs well with any t-shirt or polo. The shorts have a classic and casual design, featuring a relaxed fit and straight leg cut that provides a comfortable and flattering silhouette. They also feature front and back pockets, making them practical and convenient. These shorts are perfect for a variety of occasions, including outdoor activities, casual outings, and beach vacations. Their versatile design and comfortable fit make them a must-have item for any man\'s summer wardrobe. So, add these stylish and practical chocolate brown shorts to your collection today and step out in style this summer!', 'product_images/Male/MalePants3.jpg'),
(5, 'Sun Glasses Style', '105.00', 'Male', 'Complete your look with these stylish and functional sunglasses for men. These shades feature a classic design with a modern twist, making them perfect for any occasion. The lenses are made from high-quality materials that provide 100% UV protection, ensuring your eyes are safe from harmful rays. The frames are made from durable materials that are both lightweight and comfortable to wear. The sunglasses feature a sleek and versatile design that can be paired with any outfit, making them a great addition to any wardrobe. The dark color of the lenses and frames gives them a sophisticated and elegant look that\'s perfect for both casual and formal events. So, whether you\'re headed to the beach or attending a business meeting, these sunglasses are the perfect accessory to complete your look.', 'product_images/Male/MaleAcc1.jpg'),
(6, 'Summer Long Sleeve', '35.00', 'Female', 'Stay stylish and comfortable this summer with this lightweight long sleeve shirt for women. Made from high-quality and breathable materials, this shirt is perfect for hot weather while still providing coverage for your arms. The shirt features a loose and flowy fit, providing maximum comfort and freedom of movement. The long sleeves are lightweight and airy, making them perfect for sun protection without causing you to overheat. The shirt has a versatile and stylish design that pairs well with shorts, skirts, or jeans. The light color of the shirt gives it a summery and fresh look, while the unique and subtle patterns add a touch of sophistication and elegance. So, whether you\'re headed to a picnic or a day out shopping, this summer-style long sleeve shirt is the perfect addition to your wardrobe.', 'product_images/Female/FemaleShirt1.jpg'),
(7, 'Singlet Style', '30.00', 'Female', 'Stay cool and comfortable this summer with this stylish and practical women\'s singlet. Made from high-quality and breathable materials, this singlet is perfect for hot weather. The singlet features a sleeveless design that provides maximum freedom of movement and ventilation. It has a relaxed and comfortable fit that flatters the body without being too tight or restrictive. The singlet has a versatile and stylish design that can be worn on its own or layered with other clothes. The top is available in a range of colors and patterns, giving you plenty of options to choose from. The singlet\'s lightweight and breathable fabric ensures that you stay comfortable even on the hottest of days. It\'s perfect for a variety of occasions, including outdoor activities, gym workouts, and casual outings. So, add this stylish and practical women\'s singlet to your collection and stay cool and comfortable this summer.', 'product_images/Female/FemaleShirt2.jpg'),
(8, 'Long Loose', '72.00', 'Female', 'Upgrade your summer wardrobe with these stylish and comfortable brown pants for women. Made from high-quality and breathable materials, these pants are perfect for hot weather while still providing coverage for your legs. The pants feature a loose and flowy fit, providing maximum comfort and freedom of movement. The lightweight fabric makes them ideal for outdoor activities, while the brown color provides a classic and versatile look that can be dressed up or down. The pants have a relaxed and comfortable fit that flatters the body without being too tight or restrictive. They feature a simple and understated design with a subtle pattern, adding a touch of sophistication and elegance to your outfit. These brown pants are perfect for a range of occasions, including casual outings, picnics, and beach vacations. Pair them with a singlet or a lightweight blouse to complete your summer look. So, add these stylish and comfortable brown pants to your wardrobe and stay cool and comfortable all summer long.', 'product_images/Female/FemalePants1.jpg'),
(9, 'Short Black', '35.00', 'Female', ' Stay cool and stylish this summer with these versatile and comfortable black shorts for women. Made from high-quality materials, these shorts are perfect for hot weather and provide a flattering silhouette. The shorts feature a classic and casual design, with a straight leg cut that provides a comfortable and relaxed fit. They also have front and back pockets, making them practical and convenient. The black color of the shorts provides a sleek and versatile look that pairs well with any top or blouse. The shorts are made from breathable and lightweight materials that ensure you stay cool and comfortable in even the hottest weather. They are perfect for a variety of occasions, including casual outings, picnics, and beach vacations. So, whether you\'re running errands or lounging by the pool, these black shorts are the perfect addition to your summer wardrobe.', 'product_images/Female/FemalePants3.jpg'),
(10, 'Milk White Hat', '55.00', 'Female', 'Complete your summer look with this stylish and practical milk white hat for women. Made from high-quality materials, this hat provides both style and functionality. The milk white color of the hat provides a fresh and clean look that pairs well with any outfit. The hat features a wide brim that provides ample shade and protection from the sun\'s harmful rays. The brim is also adjustable, allowing you to customize the coverage based on your preferences. The hat is made from breathable and lightweight materials that ensure you stay cool and comfortable in even the hottest weather. It features a simple and understated design that\'s both versatile and stylish. The hat is perfect for a range of occasions, including outdoor events, beach vacations, and casual outings. So, add this milk white hat to your summer wardrobe and stay stylish and protected from the sun.', 'product_images/Female/FemaleAcc2.jpg'),
(11, 'Uni Queen', '35.00', 'Unisex', ' Get ready to slay with this stylish and empowering unisex white T-shirt. The shirt features a bold and unique logo in the center that showcases four powerful women with the word \"QUEEN\" in bold letters underneath. The graphic is printed in high-quality, vivid colors that stand out against the white background of the T-shirt. The shirt is made from soft and comfortable materials that provide a relaxed and comfortable fit for both men and women. The white color of the shirt provides a clean and fresh look that\'s perfect for summer. The shirt is versatile and can be worn with jeans, shorts, or skirts for a range of occasions. Whether you\'re heading to a concert or just running errands, this unisex white T-shirt is the perfect way to show off your confidence and strength', 'product_images/Unisex/UnisexShirt1.jpg'),
(12, 'Black NIRVANA', '60.00', 'Unisex', 'Add some grunge-inspired style to your wardrobe with this edgy and unique unisex black T-shirt. The shirt features a bold logo in the center that showcases the word \"NIRVANA\" in bold letters, with an angel graphic in the middle. The graphic is printed in high-quality, vivid colors that stand out against the black background of the T-shirt. The shirt is made from soft and comfortable materials that provide a relaxed and comfortable fit for both men and women. The black color of the shirt provides a sleek and versatile look that\'s perfect for any occasion. The shirt has a simple and understated design that\'s perfect for expressing your love for the legendary grunge band Nirvana. Whether you\'re a die-hard fan or just love the iconic logo, this unisex black T-shirt is the perfect addition to your wardrobe. Wear it with jeans, shorts, or skirts for a range of occasions, from concerts to casual outings. So, grab one for yourself or as a gift for a friend and show off your love for Nirvana in style.', 'product_images/Unisex/UnisexShirt2.jpg'),
(13, 'Uni white Essential', '125.00', 'Unisex', 'Get ready for summer with these versatile and comfortable unisex white short pants. Made from high-quality materials, these shorts provide a comfortable and relaxed fit for both men and women. The white color of the shorts provides a clean and fresh look that pairs well with any top or T-shirt. The shorts have a simple and understated design that\'s both versatile and stylish, with a straight leg cut and a comfortable elastic waistband. They also feature front and back pockets, making them practical and convenient. These white short pants are an essential piece for any summer wardrobe, perfect for a range of occasions from beach vacations to casual outings. They are made from breathable and lightweight materials that ensure you stay cool and comfortable in even the hottest weather. So, whether you\'re running errands or lounging by the pool, these essential unisex white short pants are the perfect addition to your summer wardrobe.', 'product_images/Unisex/UnisexPants1.jpg'),
(14, 'Green Loose', '105.00', 'Unisex', 'Stay comfortable and stylish with these versatile unisex green long loose pants. Made from high-quality materials, these pants provide a relaxed and comfortable fit for both men and women. The green color of the pants adds a pop of color to your wardrobe and provides a fresh and natural look. The loose fit and lightweight materials make these pants perfect for warm weather and provide plenty of airflow to keep you cool and comfortable. The pants feature an adjustable drawstring waistband, providing a custom fit that ensures comfort and security. The loose and flowing cut of these pants allows for a range of movement, making them perfect for both lounging and active wear. They also feature two front pockets, providing convenient storage for your essentials. These unisex green long loose pants are a versatile piece for any wardrobe, perfect for a range of occasions from yoga and exercise to casual outings and travel. So, add them to your wardrobe and enjoy the comfort and style they provide.', 'product_images/Unisex/UnisexPants2.jpg'),
(15, 'Uni Smile', '58.00', 'Unisex', 'Add some fun and positivity to your wardrobe with this unisex white hat featuring a smile logo. The hat is made from high-quality materials that ensure durability and comfort. The white color of the hat provides a clean and fresh look that\'s perfect for any occasion. The smile logo is printed in high-quality, vivid colors, adding a touch of playfulness to the hat. The hat has a classic and versatile design, with a curved brim and an adjustable strap at the back, providing a comfortable and secure fit for any head size. The lightweight and breathable materials ensure that the hat is comfortable to wear all day long, making it perfect for outdoor activities, beach trips, or casual outings. This unisex white hat with a smile logo is a versatile and fun accessory that\'s perfect for adding a touch of positivity to any outfit. So, grab one for yourself or as a gift for a friend and spread some joy and smiles wherever you go.', 'product_images/Unisex/UnisexAcc1.jpg'),
(16, 'Layered T', '70.00', 'Male', 'Introducing our stylish and comfortable layered T-shirt for men! This unique garment features two individual T-shirts sewn together to create a cool and casual look that\'s perfect for everyday wear. The inner layer is made from soft and breathable cotton material, while the outer layer is made from a durable blend of cotton and polyester for added comfort and longevity. The layered design of this T-shirt provides a distinctive look that\'s sure to turn heads. With a range of colors to choose from, you can mix and match to create a style that\'s all your own. Whether you\'re hanging out with friends or running errands around town, this layered T-shirt is the perfect choice for any casual occasion. So why wait? Add this versatile and trendy layered T-shirt to your wardrobe today and elevate your fashion game to the next level!', 'product_images/Male/MaleShirt3.jpeg'),
(17, 'Rose Black', '77.00', 'Male', 'Looking for a way to add some sophistication and edginess to your wardrobe? Our black men\'s shirt with a stylish rose design is the perfect choice. Made from high-quality cotton, this comfortable and durable shirt features an intricate rose design that adds a pop of color and uniqueness. The slim-fit design creates a flattering silhouette and the breathable fabric ensures that you stay cool and comfortable all day long. Whether you\'re dressing up for a night out or keeping it casual for a weekend brunch, this shirt is perfect for any occasion. So why settle for a basic shirt when you can elevate your style game with our black men\'s shirt with a rose design? Order now and stand out from the crowd!', 'product_images/Male/MaleShirt4.jpeg'),
(18, 'White Style', '86.00', 'Male', ' Add a touch of sophistication and versatility to your wardrobe with our men\'s white pants. Made from high-quality cotton material, these lightweight and comfortable pants feature a slim-fit design that flatters your silhouette. The classic white color pairs well with a variety of outfits and creates a clean and polished look. With several pockets, you can carry your essentials with ease. These pants are perfect for any occasion, whether you\'re going to a formal event or just running errands around town. So why wait? Elevate your style game with our men\'s white pants today!', 'product_images/Male/MalePants3.jpg'),
(19, 'Style Necklaces', '23.00', 'Male', 'Add a touch of modern style to your outfit with our white stainless steel necklace. Made from high-quality and durable stainless steel material, this necklace is perfect for everyday wear. The white color provides a clean and polished look that pairs well with any outfit, making it a versatile accessory. Whether you\'re dressing up for a special occasion or keeping it casual for a day out, this necklace will elevate your style game. Order now and add this sleek and modern accessory to your collection!', 'product_images/Male/MaleAcc2.jpg'),
(20, 'Black Belt', '50.00', 'Male', 'Complete your outfit with our classic black leather belt. Crafted from high-quality leather material, this belt is both stylish and durable, making it perfect for everyday wear. The sleek black color of the belt adds a touch of sophistication to any outfit, while the versatile design and adjustable fit ensure that it pairs well with a variety of styles. Whether you\'re dressing up for a formal occasion or keeping it casual, this belt is a must-have accessory that will elevate your style game. So why wait? Order now and add this timeless and practical accessory to your wardrobe!', 'product_images/Male/MaleAcc3.jpg'),
(21, 'White Long Sleeve', '38.00', 'Female', 'Stay cool and stylish this summer with our white long sleeve shirt for women. Made from high-quality cotton material, this shirt is lightweight, breathable, and perfect for hot weather. The classic white color of the shirt creates a fresh and versatile look that pairs well with a variety of outfits. With its comfortable and relaxed fit, this shirt is perfect for any casual occasion, from running errands to enjoying a day out with friends. So why wait? Order now and add this must-have summer shirt to your collection!', 'product_images/Female/FemaleShirt3.jpg'),
(22, 'Long Black Loose', '70.00', 'Female', 'Get ready for any occasion with our comfortable and stylish long black loose pants for women. Made from high-quality and breathable material, these pants are designed to keep you comfortable all day long. The loose fit of the pants creates a relaxed and effortless look that pairs well with a variety of tops and accessories. Whether you\'re dressing up for a special occasion or keeping it casual for a day out, these pants are a versatile addition to your wardrobe. The classic black color of the pants adds a touch of sophistication to any outfit, making it perfect for both formal and casual occasions. So why wait? Order now and elevate your style with our long black loose pants!', 'product_images/Female/FemalePants2.jpg'),
(23, 'Pink Bag', '89.00', 'Female', 'Add a pop of color to your outfit with our stylish and functional pink bag for women. Made from high-quality materials, this bag is durable and perfect for everyday use. The spacious interior and multiple pockets make it easy to stay organized, while the adjustable strap allows you to wear it comfortably as a shoulder or crossbody bag.\r\n\r\nWith its vibrant pink color and versatile design, this bag is perfect for any occasion. Whether you\'re heading to work or out for a night on the town, our pink bag will add a touch of fun and personality to your outfit. So why wait? Order now and add this must-have accessory to your collection!', 'product_images/Female/FemaleAcc1.jpg'),
(24, 'Pink Style', '97.00', 'Female', ' Add a pop of color to your outfit with our stylish and functional pink bag for women. Made from high-quality materials, this bag is durable and perfect for everyday use. The spacious interior and multiple pockets make it easy to stay organized, while the adjustable strap allows you to wear it comfortably as a shoulder or crossbody bag.\r\n\r\nWith its vibrant pink color and versatile design, this bag is perfect for any occasion. Whether you\'re heading to work or out for a night on the town, our pink bag will add a touch of fun and personality to your outfit. So why wait? Order now and add this must-have accessory to your collection!', 'product_images/Female/FemaleAcc3.jpg'),
(25, 'Black Tight', '44.00', 'Female', 'Show off your curves in style with our black tight shirt for women. Made from high-quality stretchy material, this shirt hugs your body in all the right places for a flattering and comfortable fit. The classic black color makes it a versatile choice that can be dressed up or down for any occasion. With its short sleeves and round neck, this shirt is perfect for warmer weather or as a layering piece in colder months. Whether you\'re heading out for a night on the town or running errands, our black tight shirt is the perfect addition to your wardrobe. So why wait? Order now and elevate your style with this must-have piece!', 'product_images/Female/FemaleShirt4.jpg'),
(26, 'Black RadioHead', '56.00', 'Unisex', 'Show off your love for music in style with our black unisex shirt featuring a Radiohead-inspired design. Made from high-quality material, this shirt is comfortable and durable, making it perfect for everyday wear. The classic black color and timeless design make it a versatile choice for both men and women. Whether you\'re a die-hard Radiohead fan or just love the unique and stylish design of this shirt, it\'s the perfect addition to your wardrobe. Order now and add this must-have piece to your collection!', 'product_images/Unisex/UnisexShirt3.jpg'),
(27, 'White cat', '52.00', 'Unisex', 'Add a touch of whimsy to your wardrobe with our white cat design unisex shirt. Made from high-quality material, this shirt is both comfortable and durable, making it perfect for everyday wear. Featuring a cute cat design on a white background, this shirt is a playful and charming choice for anyone who loves cats. The unisex design makes it suitable for both men and women. Whether you\'re dressing up or down, this shirt is a versatile choice that is sure to add a fun and stylish touch to any outfit. Order now and elevate your wardrobe with this must-have white cat design unisex shirt!', 'product_images/Unisex/UnisexShirt4.jpg'),
(28, 'Essential Brown', '125.00', 'Unisex', 'Upgrade your summer style with our essential brown unisex short pants. Made from high-quality material, these shorts are both comfortable and durable, making them perfect for all your warm weather activities. The classic and versatile brown color makes them a stylish and practical addition to any wardrobe, while the short length keeps you cool and comfortable on hot days. Whether you\'re headed to the beach, out for a hike, or just running errands around town, these essential brown unisex short pants are a must-have for any summer wardrobe. So why wait? Order now and elevate your summer style with these stylish and comfortable shorts!', 'product_images/Unisex/UnisexPants3.jpg'),
(29, 'Uni Transparent', '27.00', 'Unisex', 'Elevate your style with our unisex transparent glasses. Made from high-quality, lightweight material, these glasses are comfortable and durable for all-day wear. The sleek and modern transparent design makes them a stylish accessory for both men and women, and can be paired with any outfit for a touch of sophistication. Whether you need them for work or for everyday wear, these glasses are a must-have accessory for anyone looking to elevate their look. Don\'t wait, order now and add these unisex transparent glasses to your collection today!', 'product_images/Unisex/UnisexAcc2.jpg'),
(30, 'Uni Silver Ring', '15.00', 'Unisex', 'Our unisex silver stainless metal ring is a timeless and versatile accessory suitable for both men and women. Made from high-quality and hypoallergenic material, this durable ring is perfect for everyday wear or special occasions. The sleek and modern design with silver color makes it a stylish addition to any outfit. Order now and elevate your look with this must-have accessory!', 'product_images/Unisex/UnisexAcc3.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
